require 'pathname'

podfile_dir = Pathname.new(__FILE__).dirname.realpath
root_dir = podfile_dir.ascend.find {|p| p.join('package.json').exist? }

platform :ios, '9.0'

target 'Example' do
  pod 'FBLazyVector', :path => "#{root_dir}/node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{root_dir}/node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{root_dir}/node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{root_dir}/node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => "#{root_dir}/node_modules/react-native/"
  pod 'React-Core', :path => "#{root_dir}/node_modules/react-native/"
  pod 'React-CoreModules', :path => "#{root_dir}/node_modules/react-native/React/CoreModules"
  pod 'React-Core/DevSupport', :path => "#{root_dir}/node_modules/react-native/"
  pod 'React-RCTActionSheet', :path => "#{root_dir}/node_modules/react-native/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{root_dir}/node_modules/react-native/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{root_dir}/node_modules/react-native/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{root_dir}/node_modules/react-native/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{root_dir}/node_modules/react-native/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{root_dir}/node_modules/react-native/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{root_dir}/node_modules/react-native/Libraries/Settings"
  pod 'React-RCTText', :path => "#{root_dir}/node_modules/react-native/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{root_dir}/node_modules/react-native/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{root_dir}/node_modules/react-native/"

  pod 'React-cxxreact', :path => "#{root_dir}/node_modules/react-native/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{root_dir}/node_modules/react-native/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{root_dir}/node_modules/react-native/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{root_dir}/node_modules/react-native/ReactCommon/jsinspector"
  pod 'ReactCommon/jscallinvoker', :path => "#{root_dir}/node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{root_dir}/node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => "#{root_dir}/node_modules/react-native/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => "#{root_dir}/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{root_dir}/node_modules/react-native/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{root_dir}/node_modules/react-native/third-party-podspecs/Folly.podspec"

  pod 'react-native-image-picker', :path => root_dir
end
